# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-12 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
